name: 混淆最新版本源码
on:
    workflow_dispatch:

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 使用 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      
      - name: 管理员
        run: |
          sudo -i

      - name: 安装依赖
        run: |
          sudo apt update && apt install wget unzip nodejs npm -y

      - name: 加载脚本
        run: |
          wget https://pub-505c82ba1c844ba788b97b1ed9415e75.r2.dev/delete-all-deployments.zip
          unzip delete-all-deployments.zip && cd delete-all-deployments && npm install

      - name: 删除部署
        run: |
          CF_API_TOKEN=${{ secrets.CF_API_TOKEN }} CF_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }}> CF_PAGES_PROJECT_NAME=${{ secrets.CF_PAGES_PROJECT_NAME }} CF_DELETE_ALIASED_DEPLOYMENTS=true npm start



